// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.0.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace BookFace.Specs.Specs.Posts
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("", Description="\tIn order to protect my privacy\r\n\tAs a BookFace user\r\n\tI want to be able to restr" +
        "ict who can see my posts when I post them", SourceFile="Specs\\Posts\\Privacy.feature", SourceLine=0)]
    public partial class Feature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Privacy.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(null, 0);
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "", "\tIn order to protect my privacy\r\n\tAs a BookFace user\r\n\tI want to be able to restr" +
                    "ict who can see my posts when I post them", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Post with privacy settings", new string[] {
                "SmokeTests"}, SourceLine=6)]
        public virtual void PostWithPrivacySettings()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Post with privacy settings", new string[] {
                        "SmokeTests"});
#line 7
this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName",
                        "FriendNames"});
            table1.AddRow(new string[] {
                        "Joe",
                        "Natalie, Fred"});
            table1.AddRow(new string[] {
                        "Fred",
                        "Joe"});
            table1.AddRow(new string[] {
                        "Natalie",
                        "Joe"});
#line 8
 testRunner.Given("the following users:", ((string)(null)), table1, "Given ");
#line 15
    testRunner.When("Fred creates a post shared with friends", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName"});
            table2.AddRow(new string[] {
                        "Joe"});
            table2.AddRow(new string[] {
                        "Fred"});
#line 17
 testRunner.Then("the following users should be able to see it", ((string)(null)), table2, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName"});
            table3.AddRow(new string[] {
                        "Natalie"});
#line 23
    testRunner.And("the following users should not be able to see it", ((string)(null)), table3, "And ");
#line 28
 testRunner.When("Fred creates a post shared with public", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "UserName"});
            table4.AddRow(new string[] {
                        "Joe"});
            table4.AddRow(new string[] {
                        "Fred"});
            table4.AddRow(new string[] {
                        "Natalie"});
#line 30
 testRunner.Then("the following users should be able to see it", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
